loader changed from blue to red white
Fenrir-04/Algo-Media pull request #35
Opened 2023-05-22 14:21 UTC by muhammedanaskhan

Inintially the loader was blue, i changed it to red and white circles rotating in opposite directions

2023-05-23 02:21 UTC, muhammedanaskhan commented
https://github.com/Fenrir-04/Algo-Media/assets/72510634/de0bb5ba-22ad-473a-8b4b-bd4fc37de21f

2023-05-23 03:07 UTC, muhammedanaskhan commented
This is what i have changed it to.... initially it was blue

2023-05-23 13:11 UTC, muhammedanaskhan commented
@Fenrir-04 can you help me resolve issue with merge conflicts

2023-05-24 19:23 UTC, KOMALDEWNANI commented
> @Fenrir-04 can you help me resolve issue with merge conflicts

Could you join the discord channel for the project on the GSSOC'23 server and ask your doubts over there? Thanks!

2023-05-24 19:33 UTC, KOMALDEWNANI requested changes

2023-05-24 19:33 UTC, KOMALDEWNANI commented on src/components/Feed.jsx
Have you deleted the Loader.jsx file from the components folder?

2023-05-24 19:33 UTC, KOMALDEWNANI commented on src/components/Loader/Loader.js
Could you please rename the file to Loader.jsx?

2023-05-25 03:05 UTC, muhammedanaskhan commented
> > @Fenrir-04 can you help me resolve issue with merge conflicts
> 
> Could you join the discord channel for the project on the GSSOC'23 server and ask your doubts over there? Thanks!

Hey is there any specific channel on the server for this project bc i cant see,

2023-05-25 03:21 UTC, closed without merging